name: lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: install libwebp
        run: sudo apt-get install -y libwebp-dev
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: -E goimports -E godot
